name = "jungle_log"

[textures]
side = "jungle_log"
top = "jungle_log"
bottom = "jungle_log_top"

[[elements]]
from = [0.0, 0.0, 0.0]
to = [16.0, 16.0, 16.0]

[elements.faces.top]
texture = "#top"
enabled = true
[elements.faces.bottom]
texture = "#bottom"
enabled = true
[elements.faces.north]
texture = "#side"
enabled = true
[elements.faces.south]
texture = "#side"
enabled = true
[elements.faces.east]
texture = "#side"
enabled = true
[elements.faces.west]
texture = "#side"
enabled = true

render_type = "opaque"
collidable = true
